version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    parallelism: 6
    steps:
      - checkout
      - run:
          name: Install MySQL Client
          command: |
            sudo apt-get update
            sudo apt-get install mysql-client-core-8.0
      - run:
          name: Build the REDCap Image
          command: |
            git clone https://github.com/vanderbilt-redcap/redcap_docker
      - run:
          name: Get REDCap Source
          command: |
            git clone --branch redcap-cypress https://github.com/aldefouw/redcap_source
      - run:
          name: Start Docker REDCap Container
          command: |
            cd /home/circleci/project/redcap_docker
            docker-compose up -d
      - run:
          name: Change eDocs folder permissions
          command: |
            sudo chmod 777 /var/edocs
      - run:
          name: Configure Cypress environment
          command: |
            cd /home/circleci/project
            mv cypress.json.example > cypress.json
            mv cypress.env.json.example cypress.env.json              
      - run:
          name: Install Cypress
          command: |
            npm install
      - run:
          name: Run Tests
          command: |
            npx cypress run
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        context: REDCap Tests